######### get all contacts

GET http://localhost:8080/contacts


######## get individual contacts using localhost
GET http://localhost:8080/contacts/644abfc74b77ce94aed02001

###

GET http://localhost:8080/contacts/644ac1a04b77ce94aed02002

###

GET http://localhost:8080/contacts/644ac1564b77ce94aed02003

###

GET http://localhost:8080/contacts/644ac1f44b77ce94aed02005


######## create a new contact

POST http://localhost:8080/contacts
Content-Type: application/json

{
  "_id": "644ac1f44b77ce94aed02004",
  "firstName": "Ivery",
  "lastName": "Ramos",
  "email": "ivybooboo@cutemail.com",
  "favoriteColor": "orange",
  "birthday": "February 28, 2023"
}

###

POST http://localhost:8080/contacts
Content-Type: application/json

{
"_id": "644ac1f44b77ce94aed02008",
"firstName": "Scarlet",
"lastName": "Ramos",
"email": "scar@gmail.com",
"favoriteColor": "scarlet",
"birthday": "September 15, 2003"
}

###

POST http://localhost:8080/contacts
Content-Type: application/json

{
  "_id": "644ac1f44b77ce94aed02009",
  "firstName": "Raquel",
  "lastName": "Ramos",
  "email": "raquelsita@gmail.com",
  "favoriteColor": "purple",
  "birthday": "September 15, 2003"
}


######## update a previous contact favorite color pink

PUT http://localhost:8080/contacts/644ac1f44b77ce94aed02004
Content-Type: application/json

{
  "_id": "644ac1f44b77ce94aed02004",
  "firstName": "Ivery",
  "lastName": "Ramos",
  "email": "ivybooboo@cutemail.com",
  "favoriteColor": "pink",
  "birthday": "February 28, 2023"
}

### update a previous contact favorite color orange

PUT http://localhost:8080/contacts/644ac1f44b77ce94aed02004
Content-Type: application/json

{
"_id": "644ac1f44b77ce94aed02004",
"firstName": "Ivery",
"lastName": "Ramos",
"email": "ivybooboo@cutemail.com",
"favoriteColor": "orange",
"birthday": "February 28, 2023"
}


######## delete previous contacts.

DELETE http://localhost:8080/contacts/644ac1f44b77ce94aed02004

###

DELETE http://localhost:8080/contacts/644ac1f44b77ce94aed02008

###

DELETE http://localhost:8080/contacts/644ac1f44b77ce94aed02009